INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Farias', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_user_role(user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role(user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Aventura');

INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Cruela', '', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg', 'Na Londres dos anos 70 em meio à revolução do punk rock, Estella, uma garota inteligente e criativa determinada a fazer um nome para si através de seus designs. Ela faz amizade com uma dupla de jovens ladrões e, juntos, constroem uma vida para si nas ruas de Londres. Um dia, o talento de Estella para a moda chama a atenção da Baronesa Von Hellman, uma lenda fashion que é devastadoramente chique e assustadora. Mas o relacionamento delas desencadeia um curso de eventos e revelações que farão com que Estella abrace seu lado rebelde e se torne a Cruella má, elegante e voltada para a vingança.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Pets Monstruosos', '', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/c7dFSqZQYqNNJVpacpIGZe3gkLW.jpg', 'Em Monster Pets (Monstros de Companhia), o cão Tinkles dá o seu melhor para arranjar um amigo.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Poderoso Chefinho 2', 'Negócios da Família', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pxOiKwRvNp3zFOiuwpYpzlbmEgC.jpg', 'Tim Templeton e seu irmão mais novo Ted, o famoso Boss Baby, tornaram-se adultos, vivem por conta própria, Tim se tornou um homem de família organizado e Ted é o chefe de um grande fundo especulativo. Mas a chegada de um novo Boss Baby, com uma abordagem totalmente nova e estratégia inovadora, está prestes a unir os irmãos inimigos ... e inspirar um novo modelo nos assuntos familiares. Tim e sua esposa Carole moram no subúrbio, onde ele cuida da casa enquanto ela cozinha a panela. Eles têm dois filhos: Tabitha, uma menina de 7 anos extremamente inteligente, e Tina, sua adorável recém-nascida. Tabitha, a primeira da classe em uma escola para superdotados, adora o tio Ted e sonha em seguir seus passos, o que preocupa muito Tim, que teme perder a infância por trabalhar tanto.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Tom & Jerry', 'O Filme', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9ns9463dwOeo1CK1JU2wirL5Yi1.jpg', 'Um gato de rua chamado Tom é contratado por uma garota chamada Kayla, uma jovem empregada que trabalha em um hotel glamouroso em Nova York, para se livrar de Jerry, um rato travesso que se mudou para o hotel, antes que ele seja a ruína de um importante casamento.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Os Croods 2', 'Uma Nova Era', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/reDeoOvnih7Zv2xKXZAZL7w8KP6.jpg', 'Em Croods 2: Uma Nova Era, em busca de um habitat mais seguro, os Croods descobrem um paraíso que atende todas as suas necessidades. Entretanto, outras pessoas já moram neste lugar: Os Bettermans, uma família que se considera melhor e mais evoluída. À medida que as tensões entre os novos vizinhos começam a aumentar, uma nova ameaça impulsiona os dois clãs em uma aventura épica que os força abraçar suas diferenças, extrair forças um do outro e construir um futuro juntos.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Invocação do Mal 3', 'A Ordem do Demônio', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg', 'Revela uma história arrepiante de terror, assassinato e um mal desconhecido que chocou até os investigadores paranormais da vida real, Ed e Lorraine Warren. Um dos casos mais intrigantes de seus arquivos, começa com uma luta pela alma de um garoto, depois os leva além de tudo o que já haviam visto antes, para marcar a primeira vez na história dos EUA um suspeito de assassinato alega possessão demoníaca como defesa.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Um Lugar Silencioso', 'Parte 2', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z2UtGA1WggESspi6KOXeo66lvLx.jpg', 'Logo após os acontecimentos mortais, até mesmo dentro de casa, a família Abbott precisa agora encarar o terror mundo afora, continuando a lutar para sobreviver em silêncio. Obrigados a se aventurar pelo desconhecido, eles rapidamente percebem que as criaturas que caçam pelo som não são as únicas ameaças que os observam pelo caminho de areia.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Crocodilos', 'A Morte Te Espera', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg', 'Um casal apaixonado por aventura convence seus amigos a explorar um remoto sistema de cavernas nas florestas australianas. Com uma tempestade se aproximando, eles adentram na caverna, que começa a encher, os deixando presos com um grupo de crocodilos.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Invasão Zumbi 2', 'Península', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/d2UxKyaJ5GgzuHaSsWinFfv3g6L.jpg', 'A península coreana ficou devastada após o surto de zumbis que atingiu os passageiros de um trem-bala com destino a Busan há quatro anos. Com isso, um ex-soldado que conseguiu fugir do país, Jung-seok, tem a missão de retornar e acaba encontrando alguns sobreviventes.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Uma Noite de Crime 5', 'A Fronteira', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7yb4blyOa8gsinsFjz9hp2j1HT0.jpg', 'A trama se passará após os eventos de ‘O Ano da Eleição’ e será focada em Adela (Ana de la Reguera) e Juan (Tenoch Huerta), que encontram abrigo em um rancho no Texas, após fugirem de um cartel no México. As coisas dão errado quando um grupo de forasteiros decide continuar purgando além do tempo concedido, quando as pessoas podem violar todas e quaisquer leis.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Velozes & Furiosos 9', '', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg', 'Dominic Toretto e sua família precisam enfrentar o seu irmão mais novo Jakob, um assassino mortal que está trabalhando com uma antiga inimiga, a cyber-terrorista Cipher.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Mortal Kombat', '', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg', 'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Mulher-Maravila 1984', '', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/srYya1ZlI97Au4jUYAktDe3avyA.jpg', 'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Monster Hunter', '', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg', 'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Jumanji', 'Próxima Fase', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg', 'Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (SerDarius Blain) agora está sob a pele de Oberon.', 3);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 1, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 1, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 1, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 3, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 4, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 5, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 6, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 7, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 8, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 9, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 10, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 11, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas quis ipsum suspendisse ultrices gravida. Nunc consequat interdum varius sit amet. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Magna eget est lorem ipsum dolor sit amet consectetur adipiscing. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. A lacus vestibulum sed arcu non. Laoreet id donec ultrices tincidunt arcu. Nisl tincidunt eget nullam non nisi est. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Aliquam id diam maecenas ultricies mi eget mauris. Sem viverra aliquet eget sit amet tellus. Netus et malesuada fames ac turpis egestas sed tempus. Tortor vitae purus faucibus ornare suspendisse sed nisi.', 12, 2);
